### ISSUE TITLE
Feature: Add a way to disable scrollReset using config

### ISSUE THREAD

**Issue by hund-antonio** [hund-studio/support#2]
Add the possibility to load a custom configuration for `_app.tsx`.

Something like:

```typescript
App.config = {
	resetScroll: false,
};
```

**Comment by hund-ernesto** [comment]
Added support for basic config:

```typescript
const App: WPReactApp = () => {
	return (
		<Fragment>
			<Page />
		</Fragment>
	);
};

App.config = {
	resetScroll: true,
};

export default App;
```

Right now the only available configuration option is `resetScroll` which triggers the useScrollTop hook from core on each page loading.

Docs coming soon.
